repository_type: pipeline
nf_core_version: "3.1.0"
lint:
  files_exist:
    - conf/igenomes.config
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config: false
template:
  org: your-org
  name: genomeportrait
  description: State-of-the-art personal whole-genome sequencing analysis for recreational, ancestry and educational genomics.
  author: genomeportrait contributors
  version: 1.0.0dev
  force: false
  outdir: .
  skip_features:
    - igenomes
